version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080